# External Database with Kubernetes Secret Example
# Use this when database credentials are stored in an existing Kubernetes secret

# Disable internal PostgreSQL
postgresql:
  enabled: false

# Configure external database with existing secret
externalDatabase:
  host: "your-database-host.amazonaws.com"
  port: 5432
  database: mail2feed
  username: mail2feed_user
  # Don't specify password here - it will come from the secret
  existingSecret: "mail2feed-db-credentials"
  existingSecretPasswordKey: "password"
  sslmode: require
  connectionParams: "connect_timeout=30"

backend:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 2

pgadmin:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: mail2feed.example.com
      paths:
        - path: /
          pathType: Prefix

# Example of creating the database credentials secret:
# kubectl create secret generic mail2feed-db-credentials \
#   --namespace mail2feed-prod \
#   --from-literal=password=your-secure-password \
#   --from-literal=connection-string=postgres://mail2feed_user:your-secure-password@your-database-host.amazonaws.com:5432/mail2feed?sslmode=require