global:
  imageRegistry: ""
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

backend:
  image:
    repository: mail2feed/backend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    RUST_LOG: info
  livenessProbe:
    httpGet:
      path: /health
      port: 3001
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 3001
    initialDelaySeconds: 5
    periodSeconds: 5

frontend:
  image:
    repository: mail2feed/frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3002
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    VITE_API_URL: http://backend:3001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mail2feed.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  auth:
    database: mail2feed
    username: mail2feed_user
    password: mail2feed_password
  primary:
    persistence:
      enabled: true
      size: 8Gi
    initdb:
      scripts:
        init.sql: |
          -- Database initialization will be handled by application migrations

# External database configuration (used when postgresql.enabled = false)
externalDatabase:
  host: ""
  port: 5432
  database: mail2feed
  username: mail2feed_user
  password: ""
  # Use existing secret for database credentials
  existingSecret: ""
  existingSecretPasswordKey: "password"
  # SSL configuration
  sslmode: require  # Options: disable, allow, prefer, require, verify-ca, verify-full
  # Connection parameters
  connectionParams: ""  # Additional connection parameters

pgadmin:
  enabled: false
  image:
    repository: dpage/pgadmin4
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    PGADMIN_DEFAULT_EMAIL: admin@mail2feed.local
    PGADMIN_DEFAULT_PASSWORD: admin123
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}
tolerations: []
affinity: {}