{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail2feed.fullname" . }}-pgadmin
  labels:
    {{- include "mail2feed.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mail2feed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
{{- end }}